# Generated by Django 5.1.4 on 2024-12-17 19:52

import bandas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstiloMusical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Banda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("biografia", models.TextField()),
                (
                    "demos",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=bandas.models.banda_directory_path,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=bandas.models.banda_imagen_directory_path,
                    ),
                ),
                (
                    "lugar_ensayo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "representante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estilos_musicales",
                    models.ManyToManyField(to="bandas.estilomusical"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Integrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=100)),
                ("instrumentos_favoritos", models.CharField(max_length=200)),
                ("fecha_ingreso", models.DateField()),
                (
                    "genero_preferido",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("descripcion_personal", models.TextField(blank=True, null=True)),
                (
                    "redes_sociales",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=bandas.models.integrante_imagen_directory_path,
                    ),
                ),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="bandas.banda",
                    ),
                ),
            ],
            options={
                "unique_together": {("banda", "rol")},
            },
        ),
    ]
