# Generated by Django 5.1.4 on 2025-01-07 23:06

import bandas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0002_alter_banda_representante"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenBanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=bandas.models.banda_imagen_directory_path
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="bandas.banda",
                    ),
                ),
            ],
            options={
                "unique_together": {("banda", "id")},
            },
        ),
    ]
