# Generated by Django 5.1.4 on 2025-01-07 23:23

import bandas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0003_imagenbanda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=bandas.models.flyer_imagen_directory_path
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flyers",
                        to="bandas.banda",
                    ),
                ),
            ],
        ),
    ]
