# Generated by Django 5.1.4 on 2025-01-17 22:06

import bandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0004_flyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="banda",
            name="imagen_principal",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=bandas.models.banda_imagen_representativa_path,
            ),
        ),
    ]
